### ISSUE TITLE
More problems related to zone.js, ZoneAwarePromise and Handsontable

### ISSUE THREAD

**Issue by eitland** [handsontable/angular-handsontable#17]
### Steps to reproduce

1. I create a new project based on the starter kit on https://github.com/AngularClass/angular-starter
2. I install angular handsontable according to https://handsontable.github.io/angular-handsontable/quick-start
3. I run `yarn install`
4. I run `yarn start`
5. I expect the project to run but instead it hangs on Loading... and the console says 

In Firefox:
```
Error: Zone.js has detected that ZoneAwarePromise `(window|global).Promise` has been overwritten.
Most likely cause is that a Promise polyfill has been loaded after Zone.js (Polyfilling Promise api is not necessary when zone.js is loaded. If you must load one, do so before loading zone.js.)
Stack trace:
ac_polyfills</</</Zone.assertZonePatched@http://localhost:3000/polyfills.bundle.js:87042:23
NgZone@http://localhost:3000/main.bundle.js:5348:9
ac_main</</PlatformRef_.prototype._bootstrapModuleFactoryWithZone@http://localhost:3000/main.bundle.js:6065:22
ac_main</</PlatformRef_.prototype._bootstrapModuleWithZone/<@http://localhost:3000/main.bundle.js:6110:53
run@http://localhost:3000/main.bundle.js:122622:22
notify/<@http://localhost:3000/main.bundle.js:122635:30
flush@http://localhost:3000/main.bundle.js:134300:9
ac_polyfills</</</ZoneDelegate.prototype.invoke@http://localhost:3000/polyfills.bundle.js:87389:17
ac_polyfills</</</Zone.prototype.runGuarded@http://localhost:3000/polyfills.bundle.js:87152:28
ac_polyfills</</</Zone.prototype.wrap/<@http://localhost:3000/polyfills.bundle.js:87130:24
```

In Chrome:

```
Error: Zone.js has detected that ZoneAwarePromise `(window|global).Promise` has been overwritten.
Most likely cause is that a Promise polyfill has been loaded after Zone.js (Polyfilling Promise api is not necessary when zone.js is loaded. If you must load one, do so before loading zone.js.)
    at Function.Zone.assertZonePatched (polyfills.bundle.js:87042)
    at new NgZone (main.bundle.js:5348)
    at PlatformRef_._bootstrapModuleFactoryWithZone (main.bundle.js:6065)
    at main.bundle.js:6110
    at run (main.bundle.js:122622)
    at main.bundle.js:122635
    at MutationObserver.flush (main.bundle.js:134300)
    at ZoneDelegate.invoke (polyfills.bundle.js:87389)
    at Zone.runGuarded (polyfills.bundle.js:87152)
    at MutationObserver.<anonymous> (polyfills.bundle.js:87130)
(anonymous) @ main.bundle.js:53202
```

### Demo

A demo is available here:

https://github.com/eitland/angular-starter 

(just copied the starter repo and added angular-handsontable according to my reading of the documentation).

### Your environment
* Wrapper version: 1.0.0-beta2 
* Browser Name and version: Firefox 55.0.3 and Chrome 60.0.3112.113 
* Operating System: Windows 10 64 bit

**Comment by eitland** [comment]
Also see the description here https://github.com/handsontable/handsontable/issues/4495#issuecomment-329110036

**Comment by yehia2amer** [comment]
Hi @eitland ,
did you tried this Method: #11 

It works great for me !

**Comment by eitland** [comment]
@yehia2amer Haven't tried yet. I guess this will solve the problem but it is more than just a little bit hackish IMO so I'll keep this issue open for now.

**Comment by eitland** [comment]
OK, so I have a less hacky solution:

https://github.com/eitland/angular-starter/commit/27d3a414204a007a135c4f4ee12b495d9a19af85

and 

https://github.com/eitland/angular-starter/commit/eb3cd223f1faee16503b2f2d09427047ad8caa28

I still think this should be solved upstream though, this is just for anyone else who happen to run into the same while using angularclass (no endorsement, I prefer the official angular-cli solution).

**Comment by AMBudnik** [comment]
Thank you for sharing your thoughts. @swistach is currently out of the office until 25th of September. He'll take a look at the issue in the earliest convenience.

**Comment by ottosson** [comment]
Any progress on this issue?

I get the same error message when I build with AOT and I can't seem to get any of the suggested solutions to work =/

**Comment by ottosson** [comment]
I've made a [Stackblitz example](https://stackblitz.com/edit/angular-handsontable) to show the problem

**Comment by AMBudnik** [comment]
Sorry guys for keeping you waiting. @swistach has been given an important task that will take him at least two weeks so there is a huge possibility that we won't be able to examine this issue before the end of October.

**Comment by linktothapast** [comment]
Any update on this? We cant use Handsontable at the moment.

**Comment by isaacdcm** [comment]
Here was my fix which is implemented in an angular directive I created.  It just lets Handsontable do whatever it wants and then cleans it up.

I think that this solution could be included in the handsontable.full.js so it cleans up after itself.  Better fix would be to just put the Promise rewrite code in a testbench as opposed to the main run code.

```
declare var require: any
let Promise0 = Promise;
let Handsontable = require('handsontable-pro/dist/handsontable.full.js');
Promise = Promise0;

```

**Comment by Berus** [comment]
Hi guys :). 

Please also try to build app using (angular-cli) ng build --env --prod. Below you can check errors:

<img width="583" alt="zrzut ekranu 2017-10-31 o 13 39 47" src="https://user-images.githubusercontent.com/6708620/32224491-f74b296e-be41-11e7-92d3-dc041fff81fa.png">

ng build works fine

**Comment by fluxxu** [comment]
@Berus

```
/***************************************************************************************************
 * Zone JS is required by Angular itself.
 */
import 'handsontable';
import 'angular-handsontable';
import 'zone.js/dist/zone';
```

Import like this solves build-prod

**Comment by Berus** [comment]
@fluxxu thanks for quick response

I was trying your solution but without luck :/. I still have the same error

**Comment by kattianita** [comment]
any update on this?

**Comment by b4nt0** [comment]
shouldn't this situation be handled in USE_NATIVE (detect zone.js and do not overwrite the Promise in case of presence of zone.js)?

**Comment by Reggis** [comment]
@fluxxu Your fix works, but unfortunately only with older node version (previous lts - 6.12.0), but on current lts (8.9.1) sill logs error on startup. (e.resolve is not a function)

**Comment by linktothapast** [comment]
@Reggis Do you know if the workaround works on node 6.12.0 **with** `--aot`?

**Comment by linktothapast** [comment]
@Reggis Tried with node 8.x but no dice

**Comment by linktothapast** [comment]
Tried with node 6.x and `--aot`, and got the exact same issue:
```
Uncaught TypeError: NativePromise.resolve is not a function
```

**Comment by Reggis** [comment]
@linktothapast My configuration is:
polyfills.ts:
`/***************************************************************************************************
 * Zone JS is required by Angular itself.
 */
import 'handsontable';
import 'angular-handsontable';
import 'zone.js/dist/zone';`
package.json:
`"scripts": {
    "ng": "ng",
    "start:dev": "ng serve --host 0.0.0.0 --port 3000",
    "start:mock": "ng serve --environment mock --host 0.0.0.0 --port 3000",
    "start:mock:server": "npm-run-all -p -r json-server start:mock",
    "build": "ng build",
    "build:prod": "ng build --prod --aot",
    "build:dev": "ng build --env=dev",
    "build:mock": "ng build --env=mock",
    "json-server": "json-server json-server/db.json -r json-server/routes.json -c json-server/json-server.json",
    "test": "ng test",
    "lint": "ng lint",
    "e2e": "ng e2e"
  },`
And I'm using `npm run build:prod` command
Result of `ng -v` is:
`
    _                      _                 ____ _     ___
   / \   _ __   __ _ _   _| | __ _ _ __     / ___| |   |_ _|
  / △ \ | '_ \ / _` | | | | |/ _` | '__|   | |   | |    | |
 / ___ \| | | | (_| | |_| | | (_| | |      | |___| |___ | |
/_/   \_\_| |_|\__, |\__,_|_|\__,_|_|       \____|_____|___|
               |___/
@angular/cli: 1.4.9
node: 6.12.0
os: linux x64
@angular/animations: 4.4.6
@angular/cdk: 2.0.0-beta.8
@angular/common: 4.4.6
@angular/compiler: 4.4.6
@angular/core: 4.4.6
@angular/flex-layout: 2.0.0-beta.8
@angular/forms: 4.4.6
@angular/http: 4.4.6
@angular/material: 2.0.0-beta.8
@angular/platform-browser: 4.4.6
@angular/platform-browser-dynamic: 4.4.6
@angular/router: 4.4.6
@angular/cli: 1.4.9
@angular/compiler-cli: 4.4.6
@angular/language-service: 4.4.6
typescript: 2.3.3
`

**Comment by linktothapast** [comment]
Thanks @Reggis. I haven't tried with `@angular/cli@1.4.9`. I'm using the latest version. That's the only difference I see...

**Comment by swistach** [comment]
Actually, it's the duplicate of #34
